#import "base-utils.typ": markup, spacer
#let table = table
#let heading = heading
#let lorem = lorem
#let pad = pad
#let text = text
#let rect = rect
#let image = image
#let figure = figure
#let h = h
#let box = box
#let enum = enum
#let list = list
